### ISSUE TITLE
termios is unix only

### ISSUE THREAD

**Issue by sowdust** [ShutdownRepo/shellerator#1]
It doesn't work on windows since it's missing termios library

**Comment by ShutdownRepo** [comment]
Thanks for this issue! Does this concern the `simple_term_menu` library or something else?

**Comment by ShutdownRepo** [comment]
Okay got it. The `simple_term_menu` relies on `termios` that only works on Unix systems.
I'm working on a fix but the menu appearance won't be the same.

**Comment by ShutdownRepo** [comment]
Fixed in https://github.com/ShutdownRepo/shellerator/commit/2e28b35f37d2ab36b594f71bdd04977eb76c1bac
