### ISSUE TITLE
Feature request: Add dmenu & clipboard support

### ISSUE THREAD

**Issue by pry0cc** [ShutdownRepo/shellerator#2]
First of all, I love this idea!

I'd love to be able to press a keyboard shortcut and have a rofi / dmenu appear with a dropdown (auto selecting my port (port 8080 / preference / new available port) and my IP from my chosen network device (eth0, tun0?), and then copy the first result to my clipboard.

Imagine that.

Ctrl+shift+0 

>> Dmenu window pops up, fuzzy search type your payload "python", enter, payload is sent to clipboard to paste in and pop that shell.

Feel free to close this, I may end up making my own, but if you hadn't thought of it - that's my take :P

**Comment by ShutdownRepo** [comment]
Thank you for your idea! The last PR (#3) includes some of it. Now, there is a menu for selecting an interface and for choosing a port.

![Example (with menus)](https://raw.githubusercontent.com/ShutdownRepo/shellerator/master/assets/example-menus.gif)

On the matter of dmenu / rofi, I admit that I don't know a thing about that. I think you're this feature is very specific. So I will not add it. However, I will be happy to review any pull request including it if it blends well with the rest :)

**Comment by pry0cc** [comment]
No problem mate! Thank you for the reply 😃
