### ISSUE TITLE
Not fully working shell after printing commands.

### ISSUE THREAD

**Issue by t0-git** [ShutdownRepo/shellerator#7]
Hello,

After printing the needed commands, my terminal is not fully working. When I type something, it's not printed (but if I hit enter, it's executed, and if I hit enter multiple times, my PS1 is printed after the previous one directly, not under).

![Screenshot_2020-07-03_18-45-16](https://user-images.githubusercontent.com/52962854/86492358-6d34b380-bd5d-11ea-807c-4596626585e1.png)

Same issue if I enter the complete command (--reverse-shell etc)

---

## System

Linux blackarch 5.7.6-arch1-1 #1 SMP PREEMPT Thu, 25 Jun 2020 00:14:47 +0000 x86_64 GNU/Linux

---

## Applications

- local/python-simple-term-menu 0.6.1-1
- local/python-colorama 0.4.3-1
- local/python-argparse
- local/python-console-menu-git v0.6.0.r13.g9378508-1
- local/python-psutil 5.7.0-1
- Python 3.8.3

---

Thanks for your time :)

**Comment by ShutdownRepo** [comment]
Thanks for the issue! 
Do you encounter this problem when printing any type of shell? In this example you're echoing python ones. Do you have the same issues with nc for instance?

**Comment by t0-git** [comment]
Sorry for the inconveniance. After the last updates of the system, it works fluently. Sorry again :/
